# Generated by Django 3.1.7 on 2021-03-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphelp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
