# Generated by Django 3.1.2 on 2021-03-29 14:02

import apphelp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphelp', '0002_userprofileinfo_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='donation_pic',
            field=models.ImageField(blank=True, upload_to=apphelp.models.get_image_path),
        ),
    ]
